#!/usr/bin/env python3
from time import sleep
from datetime import datetime
from random import random
from subprocess import run
import json

from src.ui import *
from src.keys import login
import src.socks as socks
from src.contacts import load_contacts, save_contacts, display_contact, display_convo, display_messages


class Application:
    def __init__(self, public, private):
        self.public = public
        self.private = private


    def run(self):
        while True:
            try:
                self.main_menu()
            except KeyboardInterrupt:
                self.quit()


    def main_menu(self):
        """
        Runs the main loop of the program, where the user enters commands.
        
        Args:
            public: The user's public key loaded from login().
            private: The user's private key loaded from login().
        """
        self.display_help()
        commands = {"oc": self.open_conversation, 
                    "nc": self.new_contact, 
                    "lc": self.list_contacts,
                    "dc": self.delete_contact,
                    "c" : self.clear_screen,
                    "h" : self.display_help,
                    "q" : self.quit 
                    }

        while True:
            command = get_command(commands)
            self.handle_context(commands[command])


    def open_conversation(self):
        """
        Walks the user through creating a message, and sends the completed message.
        """
        contacts = load_contacts(self.private)
        print_bar("VIEW CONVERSATION")
        display_messages(contacts)
        contact_id = get_recipient(contacts)

        while True:
            display_convo(contacts[contact_id])
            message = input("Message: ").encode()
            contacts = load_contacts(self.private)

            if len(message.decode()) > 0:
                try:
                    socks.transmit(contacts[contact_id], message, self.public, self.private)
                
                except socket.error as e:
                    print_red("Error: Failed to connect to contact. Transmission cancelled.\n")
                    break
                except socket.timeout:
                    print_red("Error: Connection timed out. Transmission incomplete.\n")
                    break
                else:
                    message_receipt = { "time": datetime.now().strftime("%m/%d/%y %I:%M%p"), 
                                        "recieved": False, 
                                        "contents": message.decode()}
                    contacts[contact_id]["messages"].append(message_receipt)
                    save_contacts(contacts, private)
                    print_green("Message delivered successfully.\n")


    def new_contact(self):
        """
        Walks a user through the process of creating a new contact.

        Returns:
            The name of the contact created (used in get_recipient()).
        """
        print_bar("NEW CONTACT")
        contacts = load_contacts(self.private)

        # Get contact information
        print("Enter the information for your new contact...")
        name = input("Name: ")
        ip = get_ip()
        fingerprint = input_default("Fingerprint", None)

        # Check for duplicates
        duplicate_id = 0
        for contact_id in contacts:
            if contacts[contact_id]["name"] == name or contacts[contact_id]["ip"] == ip:
                duplicate_id = contact_id
                
        
        if duplicate_id:
            print_yellow("\n--- Warning: Contact exists ---")
            print_yellow("Existing Contact:")
            display_contact(duplicate_id, contacts)

            print_yellow("\nNew Contact:")
            print_green(name)
            print("IP:", ip)
            print("Fingerprint:", fingerprint)

            if confirm("\nUpdate contact information for {}? (Y/n) ".format(contacts[duplicate_id]["name"])):
                contacts[duplicate_id]["name"] = name
                contacts[duplicate_id]["ip"] = ip
                contacts[duplicate_id]["fingerprint"] = fingerprint
                print_green("Contact updated.\n")
            else:
                print_green("Contact update cancelled.\n")
        else:
            new_id = name + ip
            contacts[new_id] = {"name": name, "ip": ip, "fingerprint": fingerprint, "messages": []}
            print_green("Contact added.\n")

        save_contacts(contacts, self.private)

    
    def delete_contact(self):
        contacts = load_contacts(self.private)
        print_bar("DELETE CONTACT")
        contact_id = get_recipient(contacts)
        if confirm("Are you sure you would like do delete contact information for {}? (Y/n)".format(contacts[contact_id]["name"])):
            del contacts[contact_id]
            print_green("Contact deleted.\n")
            save_contacts(contacts, self.private)
        else:
            print_red("Aborted.\n")

    
    def list_contacts(self):
        """Displays each of the contacts in the contacts file."""
        contacts = load_contacts(self.private)
        print_bar("CONTACTS LIST")
        for contact_id in contacts:
            display_contact(contact_id, contacts)


    def clear_screen(self):
        run(["clear"])


    def display_help(self):
        """Displays a list of valid commands and their meanings."""
        print("Enter a command...")
        print("oc   -> Open Conversation")
        print("nc   -> New/Update Contact")
        print("lc   -> List Contacts")
        print("dc   -> Delete Contact")
        print("c    -> Clear Screen")
        print("h    -> Display help")
        print("q    -> Quit slyther\n")

    
    def quit(self):
        """Prompts the user to exit slyther."""
        if confirm("\nExit slyther? (Y/n) "):
            exit()


    def handle_context(self, func):
        try:
            func()
        except KeyboardInterrupt:
            print("\n")


if __name__ == "__main__":
    print_banner()
    public, private = login()
    
    Application(public, private).run()
    print_red("Exiting slyther...")

